spring:
  application:
    name: shopping-mall

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true                             # 실행되는 SQL을 출력
    properties:
      hibernate:
        format_sql: true                       # SQL을 보기 좋게 포맷
#        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shopping_mall
#    username: mysqluser
#    password: Mysql@3306

