spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3304/SMDB
    username: smuser
    password: User12345!@
  flyway:
    validateOnMigrate: false
    cleanDisabled: false
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: "c3RhY2t5c3RyYW5nZ2VvZnJlZW5rZXl0aGVyZXNlY3JldGVzYXJvd3Bpb25sb3diYXNlZGtleQ"
  expiration-time: 86400000 # 1일 동안 유효

cookie:
  secure: false
  sameSite: "Lax"

server:
  port: 8080

flyway-custom:
  clean_trigger: true
  migrate_trigger: true

elasticsearch:
  hostname: "localhost"
  port: 9200
  schema: "http"
