name: Deploy Spring Boot Backend

on:
  push:
    branches:
      - main
    #paths:
      #- 'shopping-mall-backend/**'
     # - '.github/workflows/deploy-backend.yml'
    #paths-ignore:
    #  - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: SSH to VPS and deploy Spring Boot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/side-mall
            git pull origin main
            docker-compose build sm-spring
            docker-compose up -d sm-spring

